import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import { IsBoolean, IsIn, IsOptional, IsString, IsUUID, MaxLength, MinLength } from 'class-validator';
import { REFUND_REASONS, type RefundReason } from '../policy/policy-schema.js';

/** A typed message, or exactly one selection (item, reason chip or yes/no chip). */
export class SendMessageDto {
  @ApiProperty({ format: 'uuid', description: 'Generated by the client per message; reuse it when retrying' })
  @IsUUID()
  clientMessageId: string;

  @ApiPropertyOptional({ maxLength: 1000 })
  @IsOptional()
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  @IsString()
  @MinLength(1)
  @MaxLength(1000)
  text?: string;

  @ApiPropertyOptional({ format: 'uuid', description: 'Item chip or item picked from the orders panel' })
  @IsOptional()
  @IsUUID()
  orderItemId?: string;

  @ApiPropertyOptional({ enum: REFUND_REASONS })
  @IsOptional()
  @IsIn(REFUND_REASONS)
  reason?: RefundReason;

  @ApiPropertyOptional({ description: 'Yes/no chip' })
  @IsOptional()
  @IsBoolean()
  answer?: boolean;
}

export class MessageViewDto {
  @ApiProperty() id: string;
  @ApiProperty({ enum: ['CUSTOMER', 'ASSISTANT'] }) role: 'CUSTOMER' | 'ASSISTANT';
  @ApiProperty() text: string;
  @ApiProperty() createdAt: string;
}

export class QuickReplyDto {
  @ApiProperty({ enum: ['ITEM', 'REASON', 'YES_NO'] }) kind: 'ITEM' | 'REASON' | 'YES_NO';
  @ApiProperty() label: string;
  @ApiPropertyOptional({ format: 'uuid' }) orderItemId?: string;
  @ApiPropertyOptional({ enum: REFUND_REASONS }) reason?: RefundReason;
  @ApiPropertyOptional() value?: boolean;
}

export class ProposalLineDto {
  @ApiProperty({ format: 'uuid' }) orderItemId: string;
  @ApiProperty() itemName: string;
  @ApiProperty() quantity: number;
  @ApiProperty({ description: 'Refundable quantity when proposed' }) maxQuantity: number;
}

export class ProposalViewDto {
  @ApiProperty({ format: 'uuid' }) orderId: string;
  @ApiProperty() orderNumber: string;
  @ApiProperty({ enum: REFUND_REASONS }) reason: RefundReason;
  @ApiProperty({ type: [ProposalLineDto] }) lines: ProposalLineDto[];
}

export class ConversationViewDto {
  @ApiProperty({ format: 'uuid' }) conversationId: string;
  @ApiProperty({ enum: ['ACTIVE', 'SUBMITTED', 'CLOSED'] }) state: string;
  @ApiProperty({ enum: ['AI', 'MANUAL'], description: 'MANUAL: show the claim form instead of chatting' }) mode: 'AI' | 'MANUAL';
  @ApiProperty({ nullable: true, type: String, description: 'Set once a claim was submitted from this conversation' }) requestId: string | null;
  @ApiProperty({ type: [MessageViewDto] }) messages: MessageViewDto[];
  @ApiProperty({ type: [QuickReplyDto] }) quickReplies: QuickReplyDto[];
  @ApiProperty({ type: ProposalViewDto, nullable: true }) proposal: ProposalViewDto | null;
}
